// Path: globaltrade-ejb/src/main/java/lk/globaltrade/session/UserAccountBean.java
package lk.globaltrade.session;

import jakarta.annotation.Resource;
import jakarta.ejb.Stateless;
import jakarta.ejb.TransactionManagement;
import jakarta.ejb.TransactionManagementType;
import jakarta.persistence.EntityManager;
import jakarta.persistence.NoResultException;
import jakarta.persistence.PersistenceContext;
import jakarta.transaction.Status;
import jakarta.transaction.UserTransaction;
import lk.globaltrade.entities.User;
import lk.globaltrade.exception.SupplyChainSystemException;
import org.mindrot.jbcrypt.BCrypt;

import java.util.List;

/**
 * Bean-managed transaction demonstration (CONTRACTS.md §9 /
 * BUILD_PLAN Step 2B). Every other session bean in this project uses
 * container-managed transactions; this one manages a UserTransaction
 * by hand deliberately, as the assignment's BMT concept demonstration.
 *
 * jBCrypt's BCrypt.gensalt() emits the "$2a$" salt prefix natively.
 * Never persist a hash generated by another tool/library here — jBCrypt
 * throws IllegalArgumentException ("Invalid salt revision") on "$2b$",
 * it does not return false, so an incompatible hash breaks login with a
 * stack trace rather than a clean auth failure.
 */
@Stateless
@TransactionManagement(TransactionManagementType.BEAN)
public class UserAccountBean implements UserAccountBeanLocal {

    private static final int BCRYPT_COST = 10;

    @PersistenceContext(unitName = "globaltradePU")
    private EntityManager em;

    @Resource
    private UserTransaction ut;

    @Override
    public User register(String name, String email, String rawPassword) {
        try {
            ut.begin();
            String hash = BCrypt.hashpw(rawPassword, BCrypt.gensalt(BCRYPT_COST));
            User user = new User(name, email, hash, User.Role.CUSTOMER);
            em.persist(user);
            ut.commit();
            return user;
        } catch (Exception e) {
            rollbackQuietly();
            // e.g. duplicate email violates the unique constraint on
            // users.email — a PersistenceException surfaced at commit.
            throw new SupplyChainSystemException("Failed to register user", e);
        }
    }

    @Override
    public User authenticate(String email, String rawPassword) {
        User user = findByEmail(email);
        if (user == null) {
            return null;
        }
        return BCrypt.checkpw(rawPassword, user.getPassword()) ? user : null;
    }

    @Override
    public void updateRole(int userId, User.Role newRole) {
        try {
            ut.begin();
            User user = em.find(User.class, userId);
            if (user != null) {
                user.setRole(newRole);
            }
            ut.commit();
        } catch (Exception e) {
            rollbackQuietly();
            throw new SupplyChainSystemException("Failed to update user role", e);
        }
    }

    @Override
    public User findByEmail(String email) {
        // Read-only lookup: a JTA-scoped EntityManager may run a query
        // outside an active UserTransaction, so no ut.begin()/commit()
        // here. This is the caller-identity resolution path used by
        // CONTRACTS.md §5 (currentUser()) and by both interceptors.
        try {
            return em.createQuery("SELECT u FROM User u WHERE u.email = :email", User.class)
                    .setParameter("email", email)
                    .getSingleResult();
        } catch (NoResultException e) {
            return null;
        }
    }

    @Override
    public List<User> findAll() {
        return em.createQuery("SELECT u FROM User u", User.class).getResultList();
    }

    private void rollbackQuietly() {
        try {
            if (ut.getStatus() != Status.STATUS_NO_TRANSACTION) {
                ut.rollback();
            }
        } catch (Exception ignored) {
            // Best-effort: we're already handling a failure; a second
            // exception from rollback() must not mask the original one.
        }
    }
}