<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>lk.globaltrade</groupId>
        <artifactId>globaltrade-scm</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>globaltrade-ear</artifactId>
    <packaging>ear</packaging>
    <name>GlobalTrade :: EAR</name>


    <dependencies>
        <dependency>
            <groupId>lk.globaltrade</groupId>
            <artifactId>globaltrade-ejb</artifactId>
            <version>${project.version}</version>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>lk.globaltrade</groupId>
            <artifactId>globaltrade-web</artifactId>
            <version>${project.version}</version>
            <type>war</type>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <version>10</version>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <generateApplicationXml>false</generateApplicationXml>

                    <modules>
                        <ejbModule>
                            <groupId>lk.globaltrade</groupId>
                            <artifactId>globaltrade-ejb</artifactId>
                            <bundleFileName>globaltrade-ejb.jar</bundleFileName>
                        </ejbModule>
                        <webModule>
                            <groupId>lk.globaltrade</groupId>
                            <artifactId>globaltrade-web</artifactId>
                            <bundleFileName>globaltrade-web.war</bundleFileName>
                            <contextRoot>/globaltrade</contextRoot>
                        </webModule>
                    </modules>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>